import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Header from '@/components/header/header'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang='en'
    >
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased bg-center bg-cover bg-no-repeat bg-[url(https://astelus.com/wp-content/viajes/la-plaza-mas-conocida-de-sevilla.jpg)]',
          inter.variable
        )}
      >
        <Header />
        {children}
      </body>
    </html>
  )
}
